'use strict';
// Ogromna baza zagadek do Word Race

function e(clue, answer) { return { clue, answer }; }

module.exports = {
  general: {
    label: '🌐 Ogólna wiedza',
    easy: [
      e('Stolica Polski', 'warszawa'), e('Największy ocean', 'spokojny'), e('Autor Quo Vadis', 'sienkiewicz'),
      e('Planeta najbliżej Słońca', 'merkury'), e('Ile sekund ma minuta?', '60'), e('Kolor nieba w dzień', 'niebieski'),
      e('Stolica Niemiec', 'berlin'), e('Ile nóg ma owad?', '6'), e('Stolica Włoch', 'rzym'),
      e('Największy kraj świata', 'rosja'), e('Ile tygodni ma rok?', '52'), e('Kto napisał Hamleta?', 'szekspir'),
      e('Stolica Francji', 'paryz'), e('Ile planet ma Układ Słoneczny?', '8'), e('Ile dni ma tydzień?', '7'),
      e('Najdłuższa rzeka świata', 'nil'), e('Stolica Japonii', 'tokio'), e('Ile oczu ma człowiek?', '2'),
      e('Ile godzin ma doba?', '24'), e('Stolica Chin', 'pekin'), e('Ile miesięcy ma rok?', '12'),
      e('Kolor trawy', 'zielony'), e('Ile palców na obu rękach?', '10'), e('Stolica Brazylii', 'brasilia'),
      e('Ile krawędzi ma sześcian?', '12'), e('Stolica Hiszpanii', 'madryt'), e('Ile liter w alfabecie polskim?', '32'),
      e('Ile wynosi 10×10', '100'), e('Symbol chemiczny wody', 'h2o'), e('Stolica Australii', 'canberra'),
    ],
    medium: [
      e('Symbol chemiczny złota', 'au'), e('Najwyższa góra świata', 'everest'), e('Rok wybuchu II Wojny Światowej', '1939'),
      e('Najdłuższa rzeka Afryki', 'nil'), e('Język programowania węży', 'python'), e('Firma za ChatGPT', 'openai'),
      e('Polska odzyskała niepodległość w roku', '1918'), e('Autor "W pustyni i w puszczy"', 'sienkiewicz'),
      e('Najszybsze zwierzę lądowe', 'gepard'), e('Rok lądowania na księżycu', '1969'),
      e('Autor teorii względności', 'einstein'), e('Ile chromosomów ma człowiek?', '46'),
      e('Stolica Australii', 'canberra'), e('Rok założenia Google', '1998'), e('Ile kości ma szkielet?', '206'),
      e('Upadek muru berlińskiego', '1989'), e('Kto odkrył Americium?', 'seaborg'), e('Stolica Kanady', 'ottawa'),
      e('Symbol chemiczny żelaza', 'fe'), e('Rok rewolucji francuskiej', '1789'), e('Ile stanów ma USA?', '50'),
      e('Autor Odysei', 'homer'), e('Kto wynalazł druk?', 'gutenberg'), e('Rok wybuchu I Wojny Światowej', '1914'),
      e('Najwyższy budynek świata', 'burj khalifa'), e('Kraj z flagą z liściem klonu', 'kanada'),
      e('Ile ton ma Ziemia? (rząd)', '6e24'), e('Prędkość światła km/s', '300000'), e('Autor "Faust"', 'goethe'),
      e('Autor "Boska Komedia"', 'dante'),
    ],
    hard: [
      e('Pierwiastek o liczbie atomowej 79', 'zloto'), e('Stolica Kazachstanu', 'astana'),
      e('Rok bitwy pod Grunwaldem', '1410'), e('Kto sformułował I zasadę termodynamiki?', 'clausius'),
      e('Rok urodzenia Kopernika', '1473'), e('Największy księżyc Saturna', 'tytan'),
      e('Kto odkrył elektron?', 'thomson'), e('Rok Wiosny Ludów', '1848'),
      e('Autor "Krytyki czystego rozumu"', 'kant'), e('Liczba Avogadro (rząd)', '6e23'),
      e('Kto odkrył promieniowanie rentgenowskie?', 'rontgen'), e('Rok bitwy pod Waterloo', '1815'),
      e('Kto sformułował prawo powszechnego ciążenia?', 'newton'), e('Rok urodzenia Mozarta', '1756'),
      e('Autor "Don Kichot"', 'cervantes'), e('Najdłuższy epicki poemat indyjski', 'mahabharata'),
      e('Rok odkrycia Ameryki', '1492'), e('Cesarz Rzymu który spalił miasto', 'neron'),
      e('Autor "Iliady"', 'homer'), e('Co to jest kwazar?', 'galaktyka aktywna'),
    ],
  },

  science: {
    label: '🔬 Nauka i technika',
    easy: [
      e('Ile nóg ma owad?', '6'), e('Co produkują rośliny w fotosyntezie?', 'tlen'), e('Jakiego koloru jest chlorofil?', 'zielony'),
      e('Ile bieguny ma magnes?', '2'), e('Jaki gaz oddychamy?', 'tlen'), e('Co to jest H2O?', 'woda'),
      e('Ile elektronów ma wodór?', '1'), e('Co bada biologia?', 'zycie'), e('Z czego zbudowany jest diament?', 'wegiel'),
      e('Ile wymiarów ma przestrzeń?', '3'), e('Co to jest DNA?', 'kwas dezoksyrybonukleinowy'),
      e('Ile par chromosomów ma człowiek?', '23'), e('Co bada astronomia?', 'kosmos'),
      e('Jak nazywa się centrum galaktyki?', 'czarna dziura'), e('Ile kg waży litr wody?', '1'),
      e('Co to jest osmoza?', 'dyfuzja wody przez membrany'), e('Co to jest fotosynteza?', 'produkcja pokarmu przez rosliny'),
      e('Ile atomów ma cząsteczka wody?', '3'), e('Co to jest enzym?', 'katalizator biologiczny'),
      e('Jak się nazywa jądro komórkowe?', 'nucleus'),
    ],
    medium: [
      e('Który gaz stanowi 78% atmosfery?', 'azot'), e('Co to jest entropia?', 'miara niesporzadku'),
      e('Kto odkrył penicylinę?', 'fleming'), e('Jak się nazywa cząstka Boga?', 'bozon higgsa'),
      e('Co to jest elektron?', 'ladunek ujemny'), e('Ile atomów ma molowa masa?', '6e23'),
      e('Co bada sejsmologia?', 'trzesienia ziemi'), e('Jak się nazywa prawa helisa DNA?', 'alfa helisa'),
      e('Co to jest mitoza?', 'podzial komorki'), e('Kto sformułował teorię ewolucji?', 'darwin'),
      e('Co to jest foton?', 'kwant swiatla'), e('Jak długo żyją neurony?', 'cale zycie'),
      e('Co to jest ATP?', 'energia komorkowa'), e('Kto odkrył radioaktywność?', 'curie'),
      e('Co to jest kwarks?', 'skladnik protonow'), e('Jak się nazywa osłona neuronu?', 'mielina'),
      e('Co to jest endocytoza?', 'pochlananie czestek przez komorke'), e('Jak się nazywa cykl Krebsa?', 'cykl kwasu cytrynowego'),
      e('Co to jest CRISPR?', 'edycja genomu'), e('Kto odkrył strukturę DNA?', 'watson crick'),
    ],
    hard: [
      e('Co to jest efekt Comptona?', 'rozpraszanie fotonow na elektronach'),
      e('Ile wynosi stała Boltzmann (rząd)?', '1e-23'), e('Co to jest supersymetria?', 'teoria czastekdualnych'),
      e('Jak się nazywa efekt kwantowy przez barierę?', 'tunelowanie'), e('Co to jest splątanie kwantowe?', 'korelacja czastekna odleglosci'),
      e('Co bada chromodynamika kwantowa?', 'silna interakcja'), e('Co to jest dekoherencja?', 'utrata splantowania'),
      e('Jak się nazywa model standardowy?', 'teoria fundamentalna czastekowych'), e('Co to jest teoria strun?', 'kwantowa grawitacja'),
      e('Co to jest holografia kwantowa?', 'zasada holograficzna'), e('Jak się nazywa zasada nieoznaczoności?', 'heisenberga'),
      e('Co to jest BEC?', 'kondensat bosego einsteina'), e('Jak się nazywa najsilniejsza siła?', 'jadrowa'),
      e('Co to jest cząstka tachyon?', 'hipotetyczna nadswietlna'), e('Jak się nazywa efekt Mössbauera?', 'bezodrzutowa emisja gamma'),
    ],
  },

  history: {
    label: '📜 Historia',
    easy: [
      e('Kto był pierwszym kosmonautą?', 'gagarin'), e('Rok wybuchu II Wojny Światowej', '1939'),
      e('Stolica Starożytnego Egiptu', 'memfis'), e('Kto zbudował Koloseum?', 'rzymianie'),
      e('W którym roku upadł mur berliński?', '1989'), e('Kto był pierwszym prezydentem USA?', 'washington'),
      e('Rok odkrycia Ameryki', '1492'), e('Gdzie odbyły się pierwsze olimpiady?', 'olimpia'),
      e('Kto napisał Iliadę?', 'homer'), e('Rok Rewolucji Francuskiej', '1789'),
      e('Kto był Egipską królową znana z urody?', 'kleopatra'), e('Jak się nazywał statek Kolumba?', 'santa maria'),
      e('Rok wybuchu I Wojny Światowej', '1914'), e('Kto był przywódcą nazistowskich Niemiec?', 'hitler'),
      e('W którym roku zakończyła się II Wojna Światowa?', '1945'), e('Kto był pierwszym człowiekiem na Księżycu?', 'armstrong'),
      e('Rok urodzenia Jezusa Chrystusa', '0'), e('Kto był cesarzem Francji?', 'napoleon'),
      e('Jak się nazywa wielka zaraza XIV w.?', 'czarna smierc'), e('W którym kraju wybuchła rewolucja w 1917?', 'rosja'),
    ],
    medium: [
      e('Rok bitwy pod Grunwaldem', '1410'), e('Autor "De Revolutionibus"', 'kopernik'),
      e('Rok upadku Konstantynopola', '1453'), e('Kto był pierwszym papieżem?', 'piotr'),
      e('Rok podpisania Magna Carta', '1215'), e('Jak długo trwała Wojna Stuletnia?', '116 lat'),
      e('Kto był władcą Mongołów?', 'czyngis chan'), e('Rok pokoju westfalskiego', '1648'),
      e('Kto odkrył antybiotyk?', 'fleming'), e('Rok urodzenia Napoleona', '1769'),
      e('Gdzie odbyła się bitwa pod Waterloo?', 'belgia'), e('Kto był ostatnim carem Rosji?', 'mikolaj 2'),
      e('Rok urodzenia Kopernika', '1473'), e('Rok rewolucji bolszewickiej', '1917'),
      e('Kto stworzył druk ruchomą czcionką?', 'gutenberg'), e('Rok unii lubelskiej', '1569'),
      e('Kto podbił Persję?', 'aleksander macedonski'), e('Rok wybuchu Powstania Warszawskiego', '1944'),
      e('Jak się nazywał statek Magellana?', 'victoria'), e('Kto założył Rzym według legendy?', 'romulus'),
    ],
    hard: [
      e('Rok śmierci Aleksandra Macedońskiego', '323 pne'), e('Jak się nazywał traktat po I WŚ?', 'wersalski'),
      e('Kto był pierwszym szachem Iranu?', 'cyrus'), e('Rok unifikacji Niemiec', '1871'),
      e('Kto wprowadził hieroglify?', 'egipcjanie'), e('Rok pierwszego wydrukowania Biblii przez Gutenberga', '1455'),
      e('Jak długo panował August?', '40 lat'), e('Kto był pierwszym konsulem Republiki Frncuskiej?', 'napoleon'),
      e('Rok bitwy pod Termopilami', '480 pne'), e('Jak się nazywa dokument Wielkiej Karty Swobód?', 'magna carta'),
      e('Kto był autorem "Historii" starożytnej?', 'herodot'), e('Rok śmierci Juliusza Cezara', '44 pne'),
      e('Jak się nazywa dynastia ostatnich cesarzy Chin?', 'qing'), e('Rok podboju Konstantynopola przez Osmanów', '1453'),
      e('Kto był autorem "Arthashastra"?', 'kautilja'),
    ],
  },

  sport: {
    label: '⚽ Sport',
    easy: [
      e('Ile graczy ma drużyna piłkarska?', '11'), e('Ile metrów ma basen olimpijski?', '50'),
      e('Ile pierścieni ma flaga olimpijska?', '5'), e('Kto biegnie najszybciej na 100m?', 'bolt'),
      e('Ile pkt daje trójka w koszykówce?', '3'), e('Jak długo trwa mecz NBA?', '48 minut'),
      e('Gdzie grają Bulls?', 'chicago'), e('Ile zawodników w siatkówce?', '6'),
      e('Ile metrów ma maraton?', '42195'), e('Co to jest hat-trick?', '3 gole jednego gracza'),
      e('Ile kręgli stoi na początku?', '10'), e('Ile setów w finale Wimbledonu?', '5'),
      e('W którym roku Polska wygrała Euro?', 'nie wygrala'), e('Ile m ma skok w dal rekord?', '8 95'),
      e('Ile min trwa mecz piłki ręcznej?', '60'), e('Ile zawodników ma drużyna rugby?', '15'),
      e('Ile pkt za try w rugby?', '5'), e('Ile rund ma mecz bokserski?', '12'),
      e('Ile cm ma wysokość siatki w siatkówce?', '243'), e('Ile metrów ma skocznia narciarska?', '120'),
    ],
    medium: [
      e('Ile razy Brazylia wygrała MŚ w piłce?', '5'), e('Kto ma najwięcej tytułów LM?', 'real madryt'),
      e('Ile Tour de France wygrał Armstrong?', '7'), e('Rekord świata w 100m kto?', 'bolt'),
      e('W którym roku Polska wygrała MŚ w siatkówce?', '2018'), e('Kto wygrał Wimbledon najwięcej razy?', 'federer'),
      e('Ile kg waży rakieta tenisowa?', 'ok 300g'), e('Gdzie jest stadion Camp Nou?', 'barcelona'),
      e('Ile wynosi rekord w skoku wzwyż?', '245'), e('Co to jest grand slam w tenisie?', 'wygranie 4 turniejow'),
      e('Ile km ma trasa maratonu górskiego?', '42'), e('Gdzie były olimpiady w 2008?', 'pekin'),
      e('Kto wygrał Tour de France 2023?', 'vingegaard'), e('Ile zawodników w drużynie hokeja?', '6'),
      e('Jak się nazywa nagroda w golfie?', 'masters'), e('Ile punktów daje snuker maksymalny?', '147'),
      e('Ile cm ma pierścień w koszykówce?', '45'), e('Ile metrów ma 110m płotki?', '110'),
      e('Kto jest najlepszym bramkarzem w historii wg FIFA?', 'lev yashin'), e('Ile zawodników w polo?', '4'),
    ],
    hard: [
      e('Rekord świata w maratonie?', '2 01 09'), e('Ile metrów ma rzut oszczepem rekord?', '98 48'),
      e('Kto pokonał Tysona jako pierwszy?', 'buster douglas'), e('Ile biegów ma F1 w sezonie 2024?', '24'),
      e('Ile wynosi rekord w skoku o tyczce?', '625'), e('Kto jest rekordzistą w trójboju siłowym?', 'ray williams'),
      e('Ile lat trwa dyskwalifikacja za doping olymp?', '4'), e('Kto wygrał WRC 2023?', 'ogier'),
      e('Ile wyścigów ma Nürburgring Nordschleife?', 'ok 22km'), e('Co to jest DNF w F1?', 'did not finish'),
      e('Ile stref DRS ma tor Monaco?', '1'), e('Kto ma rekord okrążenia w F1?', 'verstappen'),
      e('Ile kg waży piłka do rugby?', 'ok 400g'), e('Kto wygrał US Open 2023?', 'novak djokovic'),
      e('Ile zawodników bierze udział w olimpiadzie 2024?', 'ok 10500'),
    ],
  },

  technology: {
    label: '💻 Technologia',
    easy: [
      e('Kto założył Microsoft?', 'gates'), e('Kto stworzył Facebooka?', 'zuckerberg'),
      e('Ile bitów ma bajt?', '8'), e('Co to jest URL?', 'adres strony'),
      e('Jaki język stworzył Python?', 'python'), e('Co to jest RAM?', 'pamiec operacyjna'),
      e('Kto stworzył iPhone?', 'apple'), e('Co to jest CSS?', 'styl strony'),
      e('Ile GB ma 1 TB?', '1024'), e('Co to jest SQL?', 'jezyk baz danych'),
      e('Kto założył Amazon?', 'bezos'), e('Co to jest API?', 'interfejs aplikacji'),
      e('Ile bitów ma adres IPv4?', '32'), e('Co to jest HTTP?', 'protokol transferu'),
      e('Kto założył Twitter?', 'dorsey'), e('Co to jest debugging?', 'szukanie bledow'),
      e('Ile wynosi rozdzielczość 4K?', '3840x2160'), e('Co to jest kernel?', 'jadro systemu'),
      e('Kto założył Tesla?', 'musk'), e('Co to jest cache?', 'pamiec podreczna'),
    ],
    medium: [
      e('Co to jest O(n log n)?', 'zlozenosc algorytmu'), e('Kto wynalazł www?', 'berners-lee'),
      e('Co to jest Docker?', 'konteneryzacja'), e('Ile warstw ma model OSI?', '7'),
      e('Co to jest REST?', 'styl architektoniczny api'), e('Kto stworzył Linuxa?', 'torvalds'),
      e('Co to jest blockchain?', 'lancuch blokow'), e('Ile bitów ma SHA-256?', '256'),
      e('Co to jest VPN?', 'wirtualna siec prywatna'), e('Co to jest JWT?', 'token uwierzytelniania'),
      e('Jak się nazywa wzorzec pub/sub?', 'publish subscribe'), e('Co to jest TDD?', 'programowanie sterowane testami'),
      e('Ile warstw ma TCP/IP?', '4'), e('Co to jest ORM?', 'mapowanie obiektowo relacyjne'),
      e('Kto stworzył JavaScript?', 'brendan eich'), e('Co to jest CI/CD?', 'ciagle dostarczanie'),
      e('Ile bitów ma adres IPv6?', '128'), e('Co to jest ACID?', 'wlasnosci transakcji'),
      e('Co to jest GraphQL?', 'jezyk zapytan api'), e('Kto stworzył React?', 'facebook'),
    ],
    hard: [
      e('Co to jest CAP theorem?', 'spojnosc dostepnosc partycja'), e('Kto sformułował prawo Moores?', 'gordon moore'),
      e('Co to jest tail call?', 'rekurencja ogonowa'), e('Co to jest lambda calculus?', 'formalizm obliczen'),
      e('Ile tranzystorów ma M3 Ultra od Apple?', '184 miliardy'), e('Co to jest zeta-zero Riemanna?', 'matematyczny problem otwarty'),
      e('Co to jest HyperLogLog?', 'algorytm liczenia unikalnych'), e('Kto wynalazł algorytm RSA?', 'rivest shamir adleman'),
      e('Co to jest NP-hard?', 'najtrudniejsza klasa zlozenosci'), e('Co to jest SIMD?', 'rownolegle przetwarzanie danych'),
      e('Ile FLOPS ma aktualny NVIDIA H100?', 'ok 2000 teraflops'), e('Co to jest differential privacy?', 'prywatnosc statystyczna'),
      e('Co to jest federated learning?', 'rozproszony trening modelu'), e('Kto sformułował twierdzenie Goedla?', 'kurt gödel'),
      e('Co to jest qubit?', 'kwantowa jednostka informacji'),
    ],
  },

  polish_culture: {
    label: '🇵🇱 Polska i kultura',
    easy: [
      e('Stolica Polski', 'warszawa'), e('Symbol na herbie Polski', 'orzel'),
      e('Waluta polska', 'zloty'), e('Autor Pan Tadeusz', 'mickiewicz'),
      e('Ile województw ma Polska?', '16'), e('Najdłuższa rzeka Polski', 'wisla'),
      e('Najwyższy szczyt Polski', 'rysy'), e('Kto byl pierwszym królem?', 'boleslaw chrobry'),
      e('Rok odzyskania niepodległości', '1918'), e('Gdzie jest Wawel?', 'krakow'),
      e('Autor Trylogii', 'sienkiewicz'), e('Kto skomponował Mazurka Dąbrowskiego?', 'wybicki'),
      e('Jak długa jest Wisła?', '1047'), e('Autor Lalki', 'prus'),
      e('Rok uchwalenia Konstytucji 3 Maja', '1791'), e('Polska agencja kosmiczna', 'polsa'),
      e('Kto napisał Wesele?', 'wyspianski'), e('Jak się nazywa zupa z buraków?', 'barszcz'),
      e('Gdzie jest Wieliczka?', 'malopolska'), e('Rok przyjęcia chrześcijaństwa', '966'),
    ],
    medium: [
      e('Rok bitwy pod Grunwaldem', '1410'), e('Ostatni król Polski', 'stanislaw august poniatowski'),
      e('Rok Potopu Szwedzkiego', '1655'), e('Autor Dziadów', 'mickiewicz'),
      e('Rok Unii Lubelskiej', '1569'), e('Kto założył Akademię Krakowską?', 'kazimierz wielki'),
      e('Autor Ferdydurke', 'gombrowicz'), e('Rok rozbiorów Polski (I)', '1772'),
      e('Jak się nazywa największe jezioro mazurskie?', 'sniardwy'), e('Kto napisał Chłopów?', 'reymont'),
      e('Rok odbudowy Zamku Królewskiego w Warszawie', '1984'), e('Autor Popiołów', 'zeromski'),
      e('Jak się nazywa polska nagroda literacka?', 'nike'), e('Rok Powstania Kościuszkowskiego', '1794'),
      e('Kto stworzył teorię heliocentryczną?', 'kopernik'), e('Rok śmierci Jana Pawła II', '2005'),
      e('Gdzie odbyła się bitwa pod Wiedniem?', 'wiedeń'), e('Autor Nocy i dni', 'dabrowska'),
      e('Rok polskiej transformacji ustrojowej', '1989'), e('Kto był pierwszym Polakiem w kosmosie?', 'hermaszewski'),
    ],
    hard: [
      e('Rok śmierci Mieszka I', '992'), e('Autor Sonetów Krymskich', 'mickiewicz'),
      e('Rok unii polsko-litewskiej (Krewo)', '1385'), e('Kto był hetmanem pod Kłuszynem?', 'zolkiewski'),
      e('Rok bitwy pod Oliwą', '1627'), e('Autor Potopu', 'sienkiewicz'),
      e('Rok wygaśnięcia dynastii Piastów', '1370'), e('Kto był autorem Bogurodzicy?', 'nieznany'),
      e('Rok koronacji Bolesława Chrobrego', '1025'), e('Autor Dzienników Stefana Żeromskiego', 'zeromski'),
      e('Rok przyjęcia przez Polskę Konstytucji', '1791'), e('Kto był pierwszym Piastem?', 'piast kolodziej'),
      e('Rok śmierci Kazimierza Wielkiego', '1370'), e('Autor Reduty Ordona', 'mickiewicz'),
      e('Rok podpisania pokoju toruńskiego II', '1466'),
    ],
  },

  movies_series: {
    label: '🎬 Kino i seriale',
    easy: [
      e('Kto gra Iron Mana?', 'downey'), e('Rok premiery Avatar', '2009'),
      e('Reżyser Titanica', 'cameron'), e('Ile części ma LotR?', '3'),
      e('Kto zagrał Jokera w 2019?', 'phoenix'), e('Reżyser Pulp Fiction', 'tarantino'),
      e('Kto gra Sherlocka BBC?', 'cumberbatch'), e('Ile Oskarów wygrał Titanic?', '11'),
      e('Serial o Breaking Bad i metamfetaminie', 'breaking bad'), e('Platforma Stranger Things', 'netflix'),
      e('Kto gra Harrego Pottera?', 'radcliffe'), e('Reżyser Avengers Endgame', 'russo brothers'),
      e('Kto gra Gandalfa?', 'mckellen'), e('Serial o Waltera White', 'breaking bad'),
      e('Kto zagrał Jacksa Sparrowa?', 'depp'), e('Reżyser Interstellar', 'nolan'),
      e('Kto gra Batman (2022)?', 'pattinson'), e('Serial HBO o Westeros', 'game of thrones'),
      e('Kto gra Tony Soprano?', 'gandolfini'), e('Reżyser 2001 Space Odyssey', 'kubrick'),
    ],
    medium: [
      e('Oscar najlepszy film 2020', 'parasite'), e('Autor powieści "Ojciec Chrzestny"', 'puzo'),
      e('Ile sezonów ma Game of Thrones?', '8'), e('Kto reżyserował The Wire?', 'david simon'),
      e('Ile min trwa Endgame?', '181'), e('Kto gra Waltera White?', 'cranston'),
      e('Serial o domu papierowym', 'money heist'), e('Reżyser No Country for Old Men', 'coen brothers'),
      e('Kto zagrał Forresta Gumpa?', 'hanks'), e('Ile Oskarów ma Ben-Hur (1959)?', '11'),
      e('Kto reżyserował Parasite?', 'bong joon ho'), e('Serial o Johnie Snow', 'game of thrones'),
      e('Kto zagrał Hannibala Lectera?', 'anthony hopkins'), e('Reżyser Jurassic Park', 'spielberg'),
      e('Kto stworzył serię Rocky?', 'stallone'), e('Serial o Saulze Goodmanie', 'better call saul'),
      e('Kto grał Erin Brockovich?', 'julia roberts'), e('Reżyser The Godfather', 'coppola'),
      e('Ile Oskarów ma Titanic (1997)?', '11'), e('Kto gra Wolverine?', 'jackman'),
    ],
    hard: [
      e('Reżyser Stalker (1979)', 'tarkowski'), e('Kto reżyserował Rashomon?', 'kurosawa'),
      e('Rok produkcji Obywatela Kane', '1941'), e('Kto grał główną rolę w Amadeus?', 'hulce'),
      e('Reżyser Powiększenie (1966)', 'antonioni'), e('Kto reżyserował 400 Batów?', 'truffaut'),
      e('Serial HBO o terapeucie Tony Soprano', 'the sopranos'), e('Reżyser Bellissima (1951)', 'visconti'),
      e('Kto reżyserował Persona (1966)?', 'bergman'), e('Rok Metropolis Fritz Lang', '1927'),
      e('Reżyser Dogville', 'von trier'), e('Kto grał w Pi (1998)?', 'sean gullette'),
      e('Reżyser M - Morderca (1931)', 'fritz lang'), e('Kto nakręcił 8½?', 'fellini'),
      e('Kto grał w Bicycle Thieves (1948)?', 'lamberto maggiorani'),
    ],
  },
};
