// Rozbudowana baza pytań do quizu — setki pytań w wielu kategoriach
'use strict';

function q(question, answers, correct, points) {
  return { question, answers, correct, points };
}

module.exports = {

  general: {
    label: '🌐 Ogólna wiedza',
    easy: [
      q('Stolica Polski?', ['Kraków','Warszawa','Gdańsk','Wrocław'], 1, 100),
      q('Ile planet ma Układ Słoneczny?', ['7','8','9','10'], 1, 100),
      q('Ile bitów ma 1 bajt?', ['4','8','16','32'], 1, 100),
      q('Stolica Francji?', ['Lyon','Marsylia','Paryż','Bordeaux'], 2, 100),
      q('Ile godzin ma doba?', ['12','20','24','48'], 2, 100),
      q('Ile dni ma tydzień?', ['5','6','7','8'], 2, 100),
      q('Największy ocean świata?', ['Atlantyk','Indyjski','Arktyczny','Spokojny'], 3, 100),
      q('Jaki kolor uzyskamy mieszając żółty i niebieski?', ['Fioletowy','Zielony','Pomarańczowy','Brązowy'], 1, 100),
      q('Ile miesięcy ma rok?', ['10','11','12','13'], 2, 100),
      q('Ile liter ma alfabet polski?', ['30','32','35','37'], 1, 100),
      q('Stolica Niemiec?', ['Monachium','Frankfurt','Hamburg','Berlin'], 3, 100),
      q('Stolica Włoch?', ['Mediolan','Rzym','Florencja','Neapol'], 1, 100),
      q('Ile oczu ma człowiek?', ['1','2','3','4'], 1, 100),
      q('Która planeta jest najbliżej Słońca?', ['Wenus','Ziemia','Mars','Merkury'], 3, 100),
      q('Co jest symbolem chemicznym wody?', ['HO','H2O','H3O','OH'], 1, 100),
      q('Ile wynosi 10 × 10?', ['10','100','1000','10000'], 1, 100),
      q('Jaki kolor ma trawa?', ['Niebieski','Czerwony','Zielony','Żółty'], 2, 100),
      q('Ile palców ma człowiek (na obu rękach)?', ['8','9','10','12'], 2, 100),
      q('Ile sekund ma minuta?', ['30','60','90','120'], 1, 100),
      q('Stolica Hiszpanii?', ['Barcelona','Sewilla','Walencja','Madryt'], 3, 100),
      q('Ile krawędzi ma sześcian?', ['6','8','10','12'], 3, 100),
      q('Autor "Pana Tadeusza"?', ['Norwid','Słowacki','Mickiewicz','Krasicki'], 2, 100),
      q('W którym roku Polska odzyskała niepodległość?', ['1916','1917','1918','1919'], 2, 100),
      q('Ile wynosi pierwiastek z 9?', ['2','3','4','5'], 1, 100),
      q('Która pora roku następuje po lecie?', ['Wiosna','Zima','Jesień','Nie ma następnej'], 2, 100),
      q('Ile nóg ma pająk?', ['4','6','8','10'], 2, 100),
      q('Najdłuższa rzeka świata?', ['Amazonka','Nil','Jangcy','Missisipi'], 1, 100),
      q('Ile wynosi 2 do potęgi 10?', ['512','1024','2048','256'], 1, 100),
      q('Stolica Japonii?', ['Osaka','Kioto','Tokio','Hiroszima'], 2, 100),
      q('Ile skrzynek ma normalny tir (osie)?', ['2','3','4','5'], 1, 100),
    ],
    medium: [
      q('Rok założenia Google?', ['1994','1996','1998','2000'], 2, 200),
      q('Rok lądowania na księżycu?', ['1965','1967','1969','1971'], 2, 200),
      q('W którym roku Polska wstąpiła do UE?', ['2000','2002','2004','2006'], 2, 200),
      q('Najwyższy szczyt świata?', ['K2','Kangchenjunga','Mount Everest','Lhotse'], 2, 200),
      q('Kto napisał "Hamlet"?', ['Dickens','Szekspir','Molière','Cervantes'], 1, 200),
      q('Ile kości ma ludzki szkielet?', ['186','206','226','246'], 1, 200),
      q('Co oznacza skrót HTML?', ['HyperText Markup Language','HighTech Machine Learning','HyperTransfer Meta Link','HyperText Media Language'], 0, 200),
      q('Gdzie urodził się Napoleon?', ['Francja','Włochy','Korsyka','Sardynia'], 2, 200),
      q('Rok wybuchu I Wojny Światowej?', ['1912','1913','1914','1915'], 2, 200),
      q('Kto namalował Mona Lisę?', ['Michał Anioł','Rafael','Leonardo da Vinci','Botticelli'], 2, 200),
      q('Symbol chemiczny złota?', ['Go','Au','Ag','Ge'], 1, 200),
      q('Ile chromosomów ma człowiek?', ['23','44','46','48'], 2, 200),
      q('Który pierwiastek ma symbol Fe?', ['Fluor','Fosfor','Żelazo','Francez'], 2, 200),
      q('Jak nazywa się stolica Australii?', ['Sydney','Melbourne','Brisbane','Canberra'], 3, 200),
      q('Kto odkrył Amerykę w 1492?', ['Magellan','Vespucci','Kolumb','Cabot'], 2, 200),
      q('Ile wynosi π (pi) w przybliżeniu?', ['2,71','3,14','3,41','4,13'], 1, 200),
      q('Który prezydent USA zniósł niewolnictwo?', ['Washington','Jefferson','Lincoln','Roosevelt'], 2, 200),
      q('Jaka jest prędkość światła?', ['200 000 km/s','300 000 km/s','400 000 km/s','150 000 km/s'], 1, 200),
      q('Rok urodzenia Mozarta?', ['1736','1756','1776','1796'], 1, 200),
      q('Ile stanów ma USA?', ['48','49','50','51'], 2, 200),
      q('Autor "Zbrodni i kary"?', ['Tołstoj','Dostojewski','Czechow','Turgeniew'], 1, 200),
      q('Jak nazywa się stolica Brazylii?', ['Rio de Janeiro','São Paulo','Brasília','Salvador'], 2, 200),
      q('Który kraj ma największą populację?', ['USA','Indie','Chiny','Rosja'], 1, 200),
      q('Co to jest DNA?', ['Kwas deoxyRybonukleinowy','Związek azotowy','Białko enzymatyczne','Hormon wzrostu'], 0, 200),
      q('Ile planet Układu Słonecznego ma pierścienie?', ['1','2','4','6'], 2, 200),
      q('Kto stworzył teorię względności?', ['Newton','Bohr','Einstein','Curie'], 2, 200),
      q('W którym roku upadł mur berliński?', ['1987','1988','1989','1990'], 2, 200),
      q('Ile kalorii ma 1 gram tłuszczu?', ['4','7','9','11'], 2, 200),
      q('Jaka jest stolica Kanady?', ['Toronto','Vancouver','Ottawa','Montreal'], 2, 200),
      q('Ile wynosi suma kątów trójkąta?', ['90°','180°','270°','360°'], 1, 200),
    ],
    hard: [
      q('Rok urodzenia Mikołaja Kopernika?', ['1463','1473','1483','1493'], 1, 300),
      q('Jak nazywa się największy księżyc Saturna?', ['Europa','Tytan','Ganimedes','Kallisto'], 1, 300),
      q('Który pierwiastek ma największą elektroujemność?', ['Chlor','Tlen','Fluor','Azot'], 2, 300),
      q('Jak nazywa się zjawisko rozszerzenia wszechświata?', ['Efekt Dopplera','Ekspansja kosmiczna','Prawo Hubble\'a','Teoria strun'], 2, 300),
      q('Ile wynosi liczba Avogadro (rząd)?', ['10^21','10^23','10^25','10^27'], 1, 300),
      q('Kto napisał "Faust"?', ['Schiller','Brecht','Goethe','Heine'], 2, 300),
      q('Jaka jest stolica Kazachstanu?', ['Ałmaty','Szymkent','Astana','Karaganda'], 2, 300),
      q('Który rok uznaje się za koniec Cesarstwa Zachodniorzymskiego?', ['410','455','476','493'], 2, 300),
      q('Co oznacza akronim UNESCO?', ['United Nations Educational Scientific Cultural Org.','United Nations Economic Social Council','Union of Nations Economic Scientific Cooperation','Universal Nations Education Science Council'], 0, 300),
      q('Który metal jest najlepszym przewodnikiem elektryczności?', ['Miedź','Złoto','Srebro','Aluminium'], 2, 300),
      q('Ile elektronów ma atom wodoru?', ['0','1','2','3'], 1, 300),
      q('W którym roku założono firmę Apple?', ['1974','1975','1976','1977'], 2, 300),
      q('Kto napisał "Sto lat samotności"?', ['Borges','Cortázar','García Márquez','Neruda'], 2, 300),
      q('Ile wynosi stała Plancka (rząd)?', ['10^-34','10^-30','10^-26','10^-22'], 0, 300),
      q('Który element ma symbol Sb?', ['Sód','Antymon','Stront','Skand'], 1, 300),
    ],
  },

  science: {
    label: '🔬 Nauka i technika',
    easy: [
      q('Co robi chlorofil?', ['Pochłania wodę','Produkuje tlen z CO2','Trawi pokarm','Przewodzi prąd'], 1, 100),
      q('Ile wynosi temperatura wrzenia wody?', ['90°C','95°C','100°C','105°C'], 2, 100),
      q('Co to jest atom?', ['Cząsteczka','Najmniejsza cząstka pierwiastka','Jądro komórkowe','Wirus'], 1, 100),
      q('Jak nazywa się siła przyciągania Ziemi?', ['Elektromagnetyzm','Grawitacja','Ciśnienie','Tarcie'], 1, 100),
      q('Ile wynosi temperatura zamrożenia wody?', ['0°C','−5°C','5°C','−10°C'], 0, 100),
      q('Co produkują panele słoneczne?', ['Ciepło','Elektryczność','Gaz','Wodę'], 1, 100),
      q('Ile obwodów ma DNA?', ['1','2','3','4'], 1, 100),
      q('Co to jest gen?', ['Jednostka dziedziczna','Komórka nerwowa','Cząsteczka białka','Typ enzymu'], 0, 100),
      q('Jak nazywa się centrum galaktyki Drogi Mlecznej?', ['Supernowa','Czarna dziura','Pulsar','Kwasar'], 1, 100),
      q('Co to jest fotosynteza?', ['Oddychanie roślin','Produkcja pokarmu przez rośliny','Rozmnażanie roślin','Pobieranie wody'], 1, 100),
      q('Ile żeber ma człowiek?', ['20','22','24','26'], 2, 100),
      q('Co bada sejsmologia?', ['Oceany','Trzęsienia ziemi','Gwiazdy','Atmosferę'], 1, 100),
      q('Jak nazywa się największa planeta Układu Słonecznego?', ['Saturn','Neptun','Jowisz','Uran'], 2, 100),
      q('Ile elektronów może pomieścić pierwsza powłoka atomu?', ['2','4','6','8'], 0, 100),
      q('Co to jest isotop?', ['Atom z inną liczbą neutronów','Cząsteczka z ładunkiem','Atom metalu','Forma energii'], 0, 100),
    ],
    medium: [
      q('Co oznacza skrót GPU?', ['General Processing Unit','Graphics Processing Unit','Global Program Unit','Graphic Pixel Unit'], 1, 200),
      q('Który gaz stanowi ok. 78% atmosfery?', ['Tlen','Dwutlenek węgla','Azot','Argon'], 2, 200),
      q('Jak nazywa się proces podziału komórkowego?', ['Mejoza','Migracja','Mitoza','Mutacja'], 2, 200),
      q('Ile neutronów ma izotop C-14?', ['6','7','8','14'], 2, 200),
      q('Co to jest entropia?', ['Miara porządku','Miara nieporządku','Energia kinetyczna','Ciśnienie gazu'], 1, 200),
      q('Jak długo trwa rok świetlny?', ['To odległość, nie czas','365 dni','1000 lat','Milion lat'], 0, 200),
      q('Kto wynalazł żarówkę?', ['Tesla','Edison','Bell','Faraday'], 1, 200),
      q('Co to jest kwant?', ['Najmniejsza porcja energii','Typ atomu','Cząsteczka białka','Rodzaj fali'], 0, 200),
      q('Który narząd produkuje insulinę?', ['Wątroba','Nerka','Trzustka','Żołądek'], 2, 200),
      q('Jak nazywa się teoria opisująca ewolucję?', ['Teoria Mendla','Teoria Darwina','Teoria Lamarck\'a','Teoria Einsteina'], 1, 200),
      q('Co oznacza CPU?', ['Central Processing Unit','Computer Peripheral Unit','Core Power Unit','Central Program Utility'], 0, 200),
      q('Ile wynosi prędkość dźwięku w powietrzu?', ['~340 m/s','~150 m/s','~500 m/s','~1000 m/s'], 0, 200),
      q('Który narząd filtruje krew?', ['Wątroba','Serce','Płuca','Nerka'], 3, 200),
      q('Co to jest osmoza?', ['Dyfuzja wody przez membranę','Reakcja chemiczna','Typ oddychania','Forma syntezy'], 0, 200),
      q('Ile par chromosomów ma człowiek?', ['22','23','24','46'], 1, 200),
    ],
    hard: [
      q('Co to jest efekt Comptona?', ['Rozpraszanie fotonów na elektronach','Zjawisko fotoelektryczne','Interferencja fal','Dyfrakcja światła'], 0, 300),
      q('Jak nazywa się cząstka odpowiedzialna za masę?', ['Elektron','Kwark','Bozon Higgsa','Gluon'], 2, 300),
      q('Ile wynosi stała grawitacji G?', ['6,67×10^-11','9,81×10^-11','3,14×10^-11','1,38×10^-11'], 0, 300),
      q('Co to jest efekt tunelowania?', ['Przejście cząstki przez barierę potencjału','Ugięcie światła','Emisja elektronów','Spin cząstek'], 0, 300),
      q('Jak nazywa się model budowy atomu Bohra?', ['Model planetarny','Model kubiczny','Model falowy','Model sfery'], 0, 300),
    ],
  },

  history: {
    label: '📜 Historia',
    easy: [
      q('Kto był pierwszym prezydentem USA?', ['Jefferson','Lincoln','Washington','Adams'], 2, 100),
      q('W którym roku wybuchła II Wojna Światowa?', ['1937','1938','1939','1940'], 2, 100),
      q('Kto zbudował Koloseum?', ['Grecy','Egipcjanie','Rzymianie','Babilończycy'], 2, 100),
      q('Jak nazywa się wielki mur w Chinach?', ['Chiński Mur','Wielki Mur Chiński','Mur Azjatycki','Mur Dynastii Han'], 1, 100),
      q('W którym roku upadł mur berliński?', ['1985','1987','1989','1991'], 2, 100),
      q('Kto był pierwszym człowiekiem w kosmosie?', ['Armstrong','Gagarin','Titow','Glenn'], 1, 100),
      q('Gdzie odbyły się pierwsze nowożytne igrzyska olimpijskie?', ['Ateny','Rzym','Paryż','Londyn'], 0, 100),
      q('Jak nazywał się okręt Kolumba?', ['Victoria','Santa María','Pinta Niña','Nina'], 0, 100),
      q('W którym roku wybuchła Rewolucja Francuska?', ['1776','1785','1789','1793'], 2, 100),
      q('Kto napisał "Iliadę"?', ['Sofokles','Ajschylos','Homer','Eurypides'], 2, 100),
      q('Jak nazywa się pierwsza konstytucja świata?', ['Magna Carta','Konstytucja USA','Konstytucja 3 Maja','Deklaracja Niepodległości'], 2, 100),
      q('W którym mieście znajdowały się Wiszące Ogrody?', ['Babilon','Persepolis','Nikspur','Ur'], 0, 100),
      q('Kiedy Polska przystąpiła do NATO?', ['1997','1998','1999','2000'], 2, 100),
      q('Kto był ostatnim carem Rosji?', ['Aleksander III','Mikołaj I','Mikołaj II','Aleksander II'], 2, 100),
      q('W którym roku Polska weszła do Unii Europejskiej?', ['2000','2002','2004','2006'], 2, 100),
    ],
    medium: [
      q('Jak nazywa się bitwa, w której Napoleon poniósł ostateczną klęskę?', ['Austerlitz','Borodino','Lipsk','Waterloo'], 3, 200),
      q('Kto był przywódcą Związku Radzieckiego w czasie II WŚ?', ['Lenin','Trocki','Stalin','Chruszczow'], 2, 200),
      q('W którym roku odkryto Amerykę?', ['1488','1490','1492','1498'], 2, 200),
      q('Jak długo trwała Zimna Wojna?', ['~25 lat','~35 lat','~45 lat','~55 lat'], 2, 200),
      q('Kto wynalazł druk?', ['Gutenberg','Leibniz','Watt','Nobel'], 0, 200),
      q('Jak nazywa się traktat kończący I Wojnę Światową?', ['Traktat Berliński','Traktat Wersalski','Traktat Paryski','Traktat Ryski'], 1, 200),
      q('W którym roku miała miejsce rewolucja bolszewicka?', ['1915','1916','1917','1918'], 2, 200),
      q('Kto był pierwszym papieżem z Polski?', ['Jan Paweł I','Jan Paweł II','Pius XII','Benedykt XVI'], 1, 200),
      q('Jak długo trwało średniowiecze?', ['~500 lat','~700 lat','~1000 lat','~1200 lat'], 2, 200),
      q('Które imperium było największe w historii?', ['Mongołów','Brytyjskie','Rzymskie','Osmańskie'], 1, 200),
      q('W którym roku zginął Julius Cezar?', ['49 p.n.e.','44 p.n.e.','38 p.n.e.','31 p.n.e.'], 1, 200),
      q('Jak nazywał się statek, który zatonął w 1912 roku?', ['Olympic','Britannic','Titanic','Lusitania'], 2, 200),
      q('Kto był twórcą teorii heliocentrycznej?', ['Galileusz','Kepler','Kopernik','Brahe'], 2, 200),
      q('W którym roku wybuchło Powstanie Warszawskie?', ['1942','1943','1944','1945'], 2, 200),
      q('Jak nazywa się wielka zaraza XIV wieku?', ['Cholera','Dżuma','Ospa','Tyfus'], 1, 200),
    ],
    hard: [
      q('Jak długo trwała Wojna Stuletnia?', ['100 lat','116 lat','87 lat','134 lat'], 1, 300),
      q('Kto był pierwszym cesarzem Francji?', ['Karol Wielki','Ludwik XIV','Napoleon I','Filip IV'], 2, 300),
      q('W którym roku Konstantynopol padł pod naporem Turków?', ['1389','1421','1453','1492'], 2, 300),
      q('Jak nazywa się traktat, na mocy którego Polska odzyskała Gdańsk po I WŚ?', ['Ryski','Wersalski','Paryski','Berliński'], 1, 300),
      q('Jak długo rządził Ramzes II?', ['~33 lata','~46 lata','~66 lat','~80 lat'], 2, 300),
    ],
  },

  geography: {
    label: '🌍 Geografia',
    easy: [
      q('Stolica Rosji?', ['Sankt Petersburg','Moskwa','Kijów','Mińsk'], 1, 100),
      q('Jaka rzeka płynie przez Egipt?', ['Kongo','Niger','Nil','Zambezi'], 2, 100),
      q('Najwyższy szczyt Polski?', ['Kasprowy Wierch','Śnieżka','Rysy','Giewont'], 2, 100),
      q('Ile kontynentów ma Ziemia?', ['5','6','7','8'], 2, 100),
      q('Który kraj ma największą powierzchnię?', ['Kanada','USA','Chiny','Rosja'], 3, 100),
      q('Stolica Chin?', ['Szanghaj','Hongkong','Pekin','Guangzhou'], 2, 100),
      q('W jakim morzu leży Polska?', ['Czarne','Bałtyckie','Północne','Kaspijskie'], 1, 100),
      q('Jaka rzeka płynie przez Warszawę?', ['Bug','Wisła','Odra','Narew'], 1, 100),
      q('Stolica Brazylii?', ['Rio de Janeiro','São Paulo','Brasília','Salvador'], 2, 100),
      q('Który kraj jest najbardziej zaludniony?', ['Indie','Chiny','USA','Indonezja'], 0, 100),
      q('Jak nazywa się pustynia w Afryce Północnej?', ['Gobi','Sahara','Kalahari','Namib'], 1, 100),
      q('Stolica Austrii?', ['Graz','Salzburg','Wiedeń','Innsbruck'], 2, 100),
      q('Który ocean jest najmniejszy?', ['Atlantycki','Indyjski','Arktyczny','Spokojny'], 2, 100),
      q('Jaka rzeka płynie przez Paryż?', ['Ren','Rodan','Sekwana','Loara'], 2, 100),
      q('Stolica Grecji?', ['Saloniki','Ateny','Kreta','Korfu'], 1, 100),
    ],
    medium: [
      q('Jak długa jest rzeka Amazonka?', ['~4000 km','~5500 km','~6400 km','~7200 km'], 2, 200),
      q('Ile metrów ma Mount Everest?', ['8449','8649','8849','9049'], 2, 200),
      q('Stolica Indonezji?', ['Bali','Surabaja','Bandung','Dżakarta'], 3, 200),
      q('Który kraj ma największą linię brzegową?', ['Australia','Rosja','Kanada','Norwegia'], 2, 200),
      q('Jak głęboki jest Rów Mariański?', ['~8 km','~9 km','~11 km','~13 km'], 2, 200),
      q('Stolica Argentyny?', ['Montevideo','Santiago','Lima','Buenos Aires'], 3, 200),
      q('Przez ile krajów płynie Dunaj?', ['8','10','12','14'], 1, 200),
      q('Jak nazywa się najdłuższy łańcuch górski?', ['Himalaje','Andy','Góry Skaliste','Alpy'], 1, 200),
      q('Stolica Nigerii?', ['Lagos','Ibadan','Abudża','Kano'], 2, 200),
      q('Jaka jest powierzchnia Afryki?', ['~20 mln km²','~30 mln km²','~40 mln km²','~50 mln km²'], 1, 200),
      q('Przez które morze przepływa Kanał Sueski?', ['Czerwone','Śródziemne','Arabskie','Czarne'], 0, 200),
      q('Jak nazywa się największe jezioro Afryki?', ['Wiktorii','Tanganika','Malawi','Czad'], 0, 200),
      q('W którym kraju leży Kilimandżaro?', ['Kenia','Uganda','Tanzania','Etiopia'], 2, 200),
      q('Jak nazywa się rzeka graniczna między Polską a Niemcami?', ['Wisła','Warta','Bug','Odra'], 3, 200),
      q('Stolica Szwajcarii?', ['Genewa','Zurych','Berno','Bazylea'], 2, 200),
    ],
    hard: [
      q('Jak nazywa się najgłębsze jezioro świata?', ['Morze Kaspijskie','Bajkał','Titicaca','Superior'], 1, 300),
      q('Jaka jest długość równika?', ['~38 000 km','~40 000 km','~42 000 km','~44 000 km'], 1, 300),
      q('Stolica Bhutanu?', ['Paro','Thimphu','Punakha','Wangdue'], 1, 300),
      q('Jak nazywa się największy archipelag świata?', ['Karaiby','Indonezja','Filipiny','Oceania'], 1, 300),
      q('Ile krajów nie ma dostępu do morza w Europie?', ['8','12','16','20'], 2, 300),
    ],
  },

  sport: {
    label: '⚽ Sport',
    easy: [
      q('Ile graczy ma drużyna piłkarska?', ['9','10','11','12'], 2, 100),
      q('Ile metrów ma basen olimpijski?', ['25','50','75','100'], 1, 100),
      q('Ile ringów ma flaga olimpijska?', ['3','4','5','6'], 2, 100),
      q('Ile piłek używa się w krykiecie?', ['1','2','3','4'], 0, 100),
      q('Ile punktów daje trójka w koszykówce?', ['1','2','3','4'], 2, 100),
      q('Gdzie odbyły się Igrzyska Olimpijskie w 2020 roku?', ['Paryż','Londyn','Tokio','Pekin'], 2, 100),
      q('Ile partnerów ma para w tenisie deblowym?', ['1','2','3','4'], 1, 100),
      q('Ile metrów liczy maraton?', ['40 195','41 195','42 195','43 195'], 2, 100),
      q('Co oznacza "hat-trick" w piłce?', ['Asysta','3 gole jednego gracza','Żółta kartka','Rzut wolny'], 1, 100),
      q('Ile kręgli stoi na początku w kręglach?', ['8','9','10','12'], 2, 100),
      q('Jak długo trwa mecz NBA (regulacja)?', ['40','48','60','56 minut'], 1, 100),
      q('Gdzie grają "Bulls"?', ['LA','Nowy Jork','Chicago','Boston'], 2, 100),
      q('W jakiej dyscyplinie Thomas Bach jest przew. MKOl?', ['Piłka nożna','Szermierka','Tenis','Pływanie'], 1, 100),
      q('Ile zawodników gra w siatkówce po jednej stronie?', ['4','5','6','7'], 2, 100),
      q('Ile setów trzeba wygrać w tenisie mężczyzn (Slam)?', ['2','3','4','Zawsze 5'], 1, 100),
    ],
    medium: [
      q('Kto jest rekordzistą świata w 100m?', ['Bolt','Gay','Powell','Blake'], 0, 200),
      q('Ile Tour de France wygrał Lance Armstrong? (zanim odebrano)?', ['5','6','7','8'], 2, 200),
      q('Ile razy Brazylia wygrała MŚ w piłce nożnej?', ['3','4','5','6'], 2, 200),
      q('Który klub ma najwięcej tytułów Ligi Mistrzów?', ['Barcelona','Bayern','Liverpool','Real Madryt'], 3, 200),
      q('Ile długości ma ścieżka w F1 GP Monaco?', ['~3 km','~3,3 km','~3,6 km','~4,1 km'], 1, 200),
      q('Ile metrów ma skok narciarki normalny?', ['60-90','70-100','80-110','90-120 m'], 1, 200),
      q('W którym roku Polska wygrała MŚ w siatkówce mężczyzn po raz ostatni?', ['2012','2014','2016','2018'], 3, 200),
      q('Jak nazywa się najważniejszy turniej w golfa?', ['US Open','Masters','The Open','PGA Championship'], 1, 200),
      q('Ile okrążeń ma wyścig Formuły 1 przeciętnie?', ['30-40','40-50','50-70','70-80'], 2, 200),
      q('Który zawodnik wygrał najwięcej tytułów Wimbledonu?', ['Federer','Djokovic','Nadal','Sampras'], 0, 200),
      q('Jaka jest waga piórkowa w boksie?', ['~57 kg','~60 kg','~64 kg','~69 kg'], 0, 200),
      q('Ile puntków jest za try w rugby?', ['3','4','5','6'], 2, 200),
      q('Który kraj wygrał pierwsze MŚ w piłce nożnej?', ['Brazylia','Urugwaj','Argentyna','Włochy'], 1, 200),
      q('Ile gram waży piłka do tenisa stołowego?', ['2,5','2,7','2,9','3,1 g'], 1, 200),
      q('W którym mieście jest słynny stadion Camp Nou?', ['Madryt','Sewilla','Walencja','Barcelona'], 3, 200),
    ],
    hard: [
      q('Ile metrów ma rekord świata w rzucie oszczepem?', ['88 m','92 m','98 m','104 m'], 2, 300),
      q('Który sprinter jako pierwszy przebiegł 100m poniżej 10s?', ['Jesse Owens','Jim Hines','Carl Lewis','Bob Hayes'], 1, 300),
      q('Ile punktów przyznaje się za pinfall w kręglach (wszystkie w jednej grze)?', ['200','250','300','350'], 2, 300),
      q('Jaki jest czas kwalifikacyjny do maratonu olimpijskiego dla mężczyzn?', ['~2:10','~2:11','~2:11:30','~2:08:10'], 3, 300),
      q('Ile koni mechanicznych ma silnik F1?', ['~600','~800','~950','~1050'], 2, 300),
    ],
  },

  technology: {
    label: '💻 Technologia i IT',
    easy: [
      q('Co oznacza skrót CPU?', ['Computer Peripheral Unit','Central Processing Unit','Core Power Unit','Central Program Utility'], 1, 100),
      q('Co oznacza www?', ['World Wide Web','World Web Wide','Wide World Web','Web World Wide'], 0, 100),
      q('Ile bitów ma 1 bajt?', ['4','8','16','32'], 1, 100),
      q('Kto założył Microsoft?', ['Steve Jobs','Mark Zuckerberg','Bill Gates','Larry Page'], 2, 100),
      q('Jak nazywa się system operacyjny Apple?', ['Android','Windows','macOS','Linux'], 2, 100),
      q('Co oznacza RAM?', ['Random Access Memory','Read Access Module','Rapid Array Memory','Read Assign Module'], 0, 100),
      q('Jaki język programowania stworzył Guido van Rossum?', ['Java','Ruby','Python','Perl'], 2, 100),
      q('Co to jest HTML?', ['Język programowania','Język znaczników','System operacyjny','Baza danych'], 1, 100),
      q('Który system operacyjny jest open-source?', ['Windows','macOS','Linux','iOS'], 2, 100),
      q('Co to jest URL?', ['Adres strony internetowej','Typ pliku','Protokół sieciowy','Baza danych'], 0, 100),
      q('Kto stworzył Facebooka?', ['Jack Dorsey','Evan Spiegel','Mark Zuckerberg','Larry Page'], 2, 100),
      q('Co to jest SSL?', ['Typ bazy danych','Protokół szyfrowania','Język programowania','Standard grafiki'], 1, 100),
      q('W którym roku powstał internet (ARPANET)?', ['1959','1969','1979','1989'], 1, 100),
      q('Co to jest AI?', ['Advanced Internet','Artificial Intelligence','Automated Input','Analog Interface'], 1, 100),
      q('Kto napisał pierwszy popularny email?', ['Vint Cerf','Ray Tomlinson','Tim Berners-Lee','Dennis Ritchie'], 1, 100),
    ],
    medium: [
      q('Jak nazywa się algorytm sortowania o złożoności O(n log n)?', ['Bubble sort','Insertion sort','Merge sort','Selection sort'], 2, 200),
      q('Co to jest REST API?', ['Architektura oprogramowania','Typ bazy danych','Protokół sieciowy','Framework JS'], 0, 200),
      q('W jakim języku napisano jądro Linuxa?', ['C','C++','Assembly','Python'], 0, 200),
      q('Co oznacza HTTPS?', ['HTTP Secure','HTTP Standard','HTTP Stream','HTTP Sync'], 0, 200),
      q('Ile to jest 2^8?', ['128','256','512','1024'], 1, 200),
      q('Co to jest SQL?', ['Structured Query Language','Standard Query Library','System Query Logic','Simple Query Layer'], 0, 200),
      q('Czym jest Docker?', ['Edytor kodu','Konteneryzacja aplikacji','System baz danych','Framework CSS'], 1, 200),
      q('Co to jest blockchain?', ['Kryptograficzny łańcuch bloków','Typ bazy SQL','Sieć neuronowa','Protokół HTTP'], 0, 200),
      q('Jak nazywa się wzorzec MVC?', ['Model-View-Controller','Module-View-Config','Method-Value-Class','Meta-Visual-Core'], 0, 200),
      q('Co to jest latency?', ['Przepustowość','Opóźnienie sieci','Rozdzielczość ekranu','Typ protokołu'], 1, 200),
      q('Który język jest typowany statycznie?', ['Python','JavaScript','Ruby','TypeScript'], 3, 200),
      q('Co to jest CDN?', ['Content Delivery Network','Core Data Network','Cached Data Node','Cloud Domain Name'], 0, 200),
      q('Jak nazywa się pętla o nieznanej liczbie iteracji?', ['For','Do-while','While','Foreach'], 2, 200),
      q('Co to jest regex?', ['Typ pętli','Wyrażenie regularne','Klasa abstrakcyjna','Protokół REST'], 1, 200),
      q('Który framework CSS jest najpopularniejszy?', ['Bulma','Foundation','Bootstrap','Tailwind'], 2, 200),
    ],
    hard: [
      q('Co to jest P vs NP?', ['Problem złożoności obliczeniowej','Typ protokołu sieciowego','Klasa algorytmów szyfrowania','Model dystrybucji danych'], 0, 300),
      q('Jak nazywa się problem z wielowątkowością gdy wątki blokują się nawzajem?', ['Livelock','Deadlock','Starvation','Race condition'], 1, 300),
      q('Co to jest CAP theorem?', ['Twierdzenie o spójności, dostępności i partycji','Model cyklu życia aplikacji','Wzorzec projektowy','Protokół cache'], 0, 300),
      q('Co to jest tail call optimization?', ['Optymalizacja rekurencji ogonowej','Typ kompilacji JIT','Wzorzec obserwatora','Algorytm GC'], 0, 300),
      q('Co to jest AOT compilation?', ['Ahead-of-time compilation','Async Output Transform','Array Optimized Threading','Abstract Object Tree'], 0, 300),
    ],
  },

  polish: {
    label: '🇵🇱 Polska i kultura',
    easy: [
      q('Jaki ptak jest na herbie Polski?', ['Orzeł','Sokół','Kruk','Bocian'], 0, 100),
      q('Jak nazywa się waluta polska?', ['Euro','Złoty','Korona','Frank'], 1, 100),
      q('Które miasto jest stolicą Małopolski?', ['Lublin','Kraków','Rzeszów','Kielce'], 1, 100),
      q('Jak długa jest Wisła?', ['~900 km','~1047 km','~1200 km','~1500 km'], 1, 100),
      q('Ile województw ma Polska?', ['14','16','18','20'], 1, 100),
      q('Kto był pierwszym królem Polski?', ['Bolesław Chrobry','Mieszko I','Kazimierz Wielki','Władysław Łokietek'], 0, 100),
      q('Który film wygrał Oscara jako polski?', ['Ida','Zimna Wojna','Katyń','Kroll'], 0, 100),
      q('Jak nazywa się najdłuższy most w Polsce?', ['Słubicki','Siekierkowski','Rędziński','Gdański'], 2, 100),
      q('Który miesiąc jest narodowym miesiącem w Polsce?', ['Marzec','Listopad','Maj','Sierpień'], 1, 100),
      q('Gdzie mieści się Wawel?', ['Warszawie','Krakowie','Gdańsku','Poznaniu'], 1, 100),
    ],
    medium: [
      q('W którym roku Polska przyjęła chrześcijaństwo?', ['955','966','977','988'], 1, 200),
      q('Jak nazywa się największe polskie jezioro?', ['Mazur','Śniardwy','Mamry','Jeziorak'], 1, 200),
      q('Kto był ostatnim królem Polski?', ['Stanisław August Poniatowski','Jan III Sobieski','August III','Zygmunt III'], 0, 200),
      q('Ile gmin ma Warszawa?', ['1','10','18','35'], 0, 200),
      q('Jak nazywa się polska nagroda literacka?', ['Nike','Paszport','Gryf','Złote Pióro'], 0, 200),
      q('Kiedy odbyło się Powstanie Kościuszkowskie?', ['1792','1794','1796','1800'], 1, 200),
      q('Jak nazywa się największy park narodowy w Polsce?', ['Biebrzański','Kampinoski','Tatrzański','Roztoczański'], 0, 200),
      q('Kto napisał "Quo Vadis"?', ['Prus','Reymont','Sienkiewicz','Żeromski'], 2, 200),
      q('Ile ton ma największy dzwon na Wawelu?', ['5','8','11','14 ton'], 2, 200),
      q('Kto zdobył Nobla z fizyki dla Polski?', ['Curie-Skłodowska','Reymont','Szymborska','Miłosz'], 0, 200),
    ],
    hard: [
      q('W którym roku odbyła się bitwa pod Grunwaldem?', ['1400','1410','1420','1430'], 1, 300),
      q('Jak nazywa się traktat zawarty po Potopie Szwedzkim?', ['Oliwski','Welawsko-Bydgoski','Andruszowski','Żurawski'], 0, 300),
      q('Kto był hetmanem podczas bitwy pod Wiedniem?', ['Jan III Sobieski','Stefan Czarniecki','Stanisław Jabłonowski','Mikołaj Sieniawski'], 0, 300),
      q('Ile tomów liczy "Trylogia" Sienkiewicza?', ['2','3','4','5'], 1, 300),
      q('Jaki był pseudonim Tadeusza Kościuszki?', ['Kos','Naczelnik','Grom','Orzeł'], 1, 300),
    ],
  },

  movies: {
    label: '🎬 Kino i seriale',
    easy: [
      q('Kto gra Iron Mana w MCU?', ['Chris Evans','Robert Downey Jr.','Chris Hemsworth','Mark Ruffalo'], 1, 100),
      q('W którym roku wyszedł Avatar?', ['2007','2008','2009','2010'], 2, 100),
      q('Jak nazywa się serial o Breaking Bad?', ['Breaking Bad','Breaking Good','Bad Breaking','Break it Bad'], 0, 100),
      q('Kto reżyserował Titanica?', ['Spielberg','Nolan','Cameron','Fincher'], 2, 100),
      q('Ile części ma trylogia Władcy Pierścieni?', ['2','3','4','5'], 1, 100),
      q('Jak nazywa się platforma z "Stranger Things"?', ['HBO','Amazon','Netflix','Disney+'], 2, 100),
      q('Kto zagrał Jokera w filmie z 2019?', ['Heath Ledger','Joaquin Phoenix','Jack Nicholson','Jared Leto'], 1, 100),
      q('Jak nazywa się reżyser Pulp Fiction?', ['Scorsese','Coppola','Tarantino','Lynch'], 2, 100),
      q('Ile oskarów wygrał Titanic?', ['9','11','13','14'], 1, 100),
      q('Kto gra Sherlocka Holmesa w serialu BBC?', ['Martin Freeman','Benedict Cumberbatch','Tom Hiddleston','Andrew Scott'], 1, 100),
    ],
    medium: [
      q('Który film wygrał Oscara za Najlepszy Film w 2020?', ['1917','Joker','Parasite','Irishman'], 2, 200),
      q('Kto napisał powieść, na której oparty jest "Ojciec Chrzestny"?', ['Mario Puzo','Truman Capote','Francis Coppola','Gay Talese'], 0, 200),
      q('Jaki jest prawdziwy budżet Avengers: Endgame?', ['~150 mln$','~250 mln$','~350 mln$','~400 mln$'], 3, 200),
      q('Kto grał w filmie "Piękny umysł"?', ['Matt Damon','Russell Crowe','Tom Hanks','Leonardo DiCaprio'], 1, 200),
      q('Jak długi jest film "The Lord of the Rings: Return of the King" (extended)?', ['~3h','~3h30m','~4h','~4h10m'], 3, 200),
      q('Który film Nolana chronologicznie pokazuje odwrócony czas?', ['Memento','Interstellar','Tenet','Inception'], 2, 200),
      q('Ile sezonów ma "Game of Thrones"?', ['6','7','8','9'], 2, 200),
      q('Kto jest twórcą serialu "The Wire"?', ['David Chase','David Simon','Vince Gilligan','Matthew Weiner'], 1, 200),
      q('Który film Pixara zarobił najwyżej?', ['Toy Story 4','Incredibles 2','Finding Dory','The Lion King (2019)'], 1, 200),
      q('Kto zagrał w "Matrix" Neo?', ['Brad Pitt','Keanu Reeves','Tom Cruise','Johnny Depp'], 1, 200),
    ],
    hard: [
      q('Kto wyreżyserował "Stalker" (1979)?', ['Eisenstein','Tarkowski','Godard','Bergman'], 1, 300),
      q('Ile Oskarów wygrał "Ben-Hur" (1959)?', ['9','10','11','12'], 2, 300),
      q('Jak nazywa się technika filmowania stosowana przez Kubricka w "The Shining"?', ['Dolly zoom','Steadicam','Rack focus','Wipe cut'], 1, 300),
      q('W którym roku nakręcono "Obywatela Kane"?', ['1937','1939','1941','1943'], 2, 300),
      q('Który reżyser nakręcił "Rashomon"?', ['Mizoguchi','Ozu','Kurosawa','Naruse'], 2, 300),
    ],
  },

  music: {
    label: '🎵 Muzyka',
    easy: [
      q('Jak nazywa się team Coldplay?', ['Coldplay','Coldwave','Cold Orchestra','Cold Fusion'], 0, 100),
      q('Kto zaśpiewał "Thriller"?', ['Prince','Michael Jackson','Madonna','Elton John'], 1, 100),
      q('Ile strun ma gitara klasyczna?', ['4','5','6','7'], 2, 100),
      q('Jak nazywa się polska wokalistka znana jako "Kayah"?', ['Katarzyna Szczot','Katarzyna Okuniewska','Katarzyna Pietrzak','Katarzyna Olbińska'], 1, 100),
      q('Z ilu nut składa się oktawa?', ['7','8','9','12'], 1, 100),
      q('Kto stworzył Beethoven?', ['Bacha','Mozart','Beethovena','Brahmsa'], 2, 100),
      q('Jak nazywa się nuta o połowę dłuższa od całej?', ['Ósemka','Ćwierćnuta','Półnuta','Trzyćwierćnuta'], 2, 100),
      q('Ile bitów ma typowy utwór MP3 w sekundzie?', ['64 kbps','128 kbps','256 kbps','320 kbps'], 1, 100),
      q('Kto śpiewa "Bohemian Rhapsody"?', ['AC/DC','The Beatles','Queen','Led Zeppelin'], 2, 100),
      q('Ile oktaw ma typowa ludzka skala wokalna?', ['1','2','3','4'], 1, 100),
    ],
    medium: [
      q('W którym roku The Beatles się rozpadli?', ['1968','1969','1970','1971'], 2, 200),
      q('Kto napisał "4 Seasons" (Cztery Pory Roku)?', ['Bach','Händel','Vivaldi','Monteverdi'], 2, 200),
      q('Ile albumów studyjnych nagrał Michael Jackson solo?', ['6','7','8','10'], 2, 200),
      q('Jak nazywa się rytm 3/4?', ['Tango','Walc','Polka','Marsz'], 1, 200),
      q('Kto skomponował "Requiem"? (niedokończone)', ['Haydn','Salieri','Beethoven','Mozart'], 3, 200),
      q('Jaki instrument gra Yo-Yo Ma?', ['Skrzypce','Pianino','Wiolonczela','Altówka'], 2, 200),
      q('Które miasto jest kolebką jazzu?', ['Chicago','Detroit','Memphis','Nowy Orlean'], 3, 200),
      q('Kto jest "Królem Rocka"?', ['Jimi Hendrix','Elvis Presley','Chuck Berry','Jerry Lee Lewis'], 1, 200),
      q('W jakiej tonacji jest "Moonlight Sonata"?', ['E-dur','G-mol','cis-mol','a-mol'], 2, 200),
      q('Ile symfonii napisał Beethoven?', ['7','8','9','10'], 2, 200),
    ],
    hard: [
      q('Który system temperacji muzycznej jest najczęściej stosowany współcześnie?', ['Temperacja pitagorejska','Temperacja średniotonowa','Temperacja równomiernie podzielona','Temperacja Kirnbergera'], 2, 300),
      q('Jak nazywa się zapis muzyczny bez basu?', ['Kontrapunkt','Monodia','Chorał','Heterofonia'], 0, 300),
      q('Ile partii głosowych ma typowa fuga Bacha?', ['2','3','4','5'], 2, 300),
      q('Co to jest serializm?', ['Technika kompozytorska oparta na seriach dźwięków','Styl jazzowy','Forma sonatowa','Typ improwizacji'], 0, 300),
      q('Kto skomponował "Pierrot Lunaire"?', ['Webern','Berg','Schönberg','Mahler'], 2, 300),
    ],
  },

};
